[source]
name = "Cr8tor PoC Connection"
type = "DatabricksSQL"
host_url = "https://<databricks_workspace_id>.azuredatabricks.net"
http_path = "/sql/1.0/warehouses/<sql_warehouse_id>"
port = 443
catalog = "databricks_catalog_name"

[credentials]
provider = "AzureKeyVault"
spn_clientid = "databricksspnclientid"
spn_secret = "databricksspnsecret"
