name: Keep Runner Alive Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every 1 day at 12:00 AM UTC

jobs:
  Keep-Alive:
    runs-on: [{{ cookiecutter.environment.lower() }}-cr8tor-vm]

    steps:
      - name: Keep Alive
        shell: pwsh
        run: Write-Host "Keeping the runner alive..."