name: Keep Runner Alive Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */240 * * *" # Runs every 10 days

jobs:
  Keep-Alive:
{% raw %}
    runs-on: ${{ matrix.runner }}
{% endraw %}
    strategy:
      matrix:
        runner: [{{ cookiecutter.environment }}-cr8tor-vm]

    steps:
      - name: Print Message
{% raw %}
        run: echo "Keeping Runner ${{ matrix.runner }} Alive"
{% endraw %}