name: Orchestrate Data Load

on:
    workflow_dispatch:
{% raw %}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false
{% endraw %}
jobs:
    RunOrchestrator:
      uses: lsc-sde-crates/cr8tor/.github/workflows/orchestrator.yml@develop
      #uses: ./../cr8tor/.github/workflows/orchestrator.yml
      name: Run Orchestrator
      with:
        environment: {{ cookiecutter.environment }}
      secrets: inherit