name = "dataset_1"
description = "Metadata of required tables/columns. Provide schema_name. Tables and columns are optional."
schema_name = "requested_schema_name"

[[tables]]
name = "requested_table_name"

[[tables.columns]]
name = "requested_column_1_name"

[[tables.columns]]
name = "requested_column_2_name"
