[[metadata_sources]]
file = "metadata/dataset_1.toml"

[project]
description = "{{ cookiecutter.project_description }}"
reference = "{{ cookiecutter.__project_slug }}"
name = "{{ cookiecutter.project_name }}"
project_name = "{{ cookiecutter.project_name }}"

[project.destination]
type = "{{ cookiecutter.destination_type }}"
name = "{{ cookiecutter.__destination_name }}"
format = "{{ cookiecutter.destination_format }}"

[repository]
codeRepository = "https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.__project_slug }}"
description = "This RO-Crate is versioned and stored in a Git repository on GitHub."
name = "Github Repo"

[requesting_agent]
name = "{{ cookiecutter.requester }}"

[requesting_agent.affiliation]
name = "{{ cookiecutter.requester_affiliation }}"
url = "{{ cookiecutter.requester_affiliation_url }}"