project:
  name: "{{ cookiecutter.project_name }}"
  description: "{{ cookiecutter.project_description }}"
  identifier: "cr8-{{ cookiecutter.__project_slug }}"

repository:
  name: "Github Repo"
  description: "This LSC-DIP RO-Crate is versioned and stored in a Git repository on GitHub."
  url: "https://github.com/lsc-sde-crates/"

requester:
  name: "{{ cookiecutter.requester }}"
  affiliation:
    name: "{{ cookiecutter.requester_affiliation }}"
    url: "{{ cookiecutter.requester_affiliation_url }}"

metadata_sources:
  - metadata/dataset_01.yaml
