environment:
  name: "{{ cookiecutter.environment | lower }}-tre"

resources:
  - name: jupyterhub
    resource_type: Jupyter
    url: https://jupyter.example.org
    enabled: true
    auth: oidc

  - name: guacamole
    resource_type: VDI
    enabled: true

  - name: rstudio
    resource_type: RStudio
    url: https://rstudio.example.org
    enabled: false

  - name: gitea
    resource_type: Gitea
    url: https://gitea.example.org
    enabled: false
