[bagit-info]
Source-Organization = '{{ cookiecutter.__source_organisation }}'
Organization-Address = '{{ cookiecutter.__organisation_address }}'
Contact-Name = "{{ cookiecutter.__contact_team }}"
Contact-Email = "{{ cookiecutter.__contact_email }}"
